### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by AbhijeetMankani** [CodingTrain/Genuary-Day18-VHS#1]
Dear Dan,
**You forgot to save before uploading the files...**
Hence, we have a very not **_so new version_** here... Please update it _as soon as possible
The version only has a rotating hand.

**Comment by shiffman** [comment]
Oh! Fixing this now (I hope)

**Comment by shiffman** [comment]
Let me know if this looks right to you! 

https://github.com/CodingTrain/Genuary-Day18-VHS/blob/main/Genuary_VHS/Genuary_VHS.pde

**Comment by AbhijeetMankani** [comment]
Yes, Looks good now! 👍  Thanks! 😃
